entryPoints:
  http:
    address: ":80"

providers:
  docker: {}

  file:
    directory: /rules
    watch: true

log:
  level: DEBUG

experimental:
  localPlugins:
    traefik_oauth_upstream:
      moduleName: github.com/J4NS-R/traefik-oauth-upstream
  plugins:
    demoplugin:
      moduleName: github.com/traefik/plugindemo
      version: v0.2.1
